Traceback (most recent call last):
  File "/home/pi/smartmirror/app.py", line 4, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
Traceback (most recent call last):
  File "/home/pi/smartmirror/app.py", line 4, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
Traceback (most recent call last):
  File "/home/pi/smartmirror/app.py", line 4, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
Traceback (most recent call last):
  File "/home/pi/smartmirror/app.py", line 4, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
Traceback (most recent call last):
  File "/home/pi/smartmirror/app.py", line 4, in <module>
    from flask_cors import CORS
ModuleNotFoundError: No module named 'flask_cors'
